app/components/Search.js

I think this is the tiniest pull request in the entire world

Auto focus on the search box

---

__tests__/main.test.js
appveyor.yml
package.json
yarn.lock

feat: tests / CI

---

appveyor.yml

fix: tweak build artificts

---

main.js
package.json
tray.js

Add Tray Icon and ability to hide main windows while icon remains in tray.

feat: add tray icon with open and close

---

__tests__/app/app.test.js

chore: more tests

---

main.js
package.json
yarn.lock

Allow tracking of users placement of window upon quitting the application.

feat: Keep track of windows bounds on quit

---

main.js

Address typo in config savings

fix: Update typo in windows bounds

---

package.json
yarn.lock

Support 32bit and 64bit Arch in one installer.

fix(#22): Support 32bit arch and 64bit one installer

---

LICENSE

chore: add License file

---

app/containers/Root.js
package.json

Functions probs need to be in their own file, secluded away to preserve their purity from the rest of the code. #brutal #coldAsIce
@ryanSN

[WIP] Search by Levenshtein similarity

---

README.md
main.js

feat: Global shortcut ctrl+shift+e

---

app/app-update.yml
appveyor.yml
main.js
package.json
updater.js
yarn.lock

Add Auto update logic to resolve #27

feature: Auto Update

---

appveyor.yml
package.json
yarn.lock

fixes: #42
fixes: #43 
fixes: #44

fix: Electron builder errors

---

package.json
yarn.lock

Update react to 16, to close out the 3 greenkeeper tickets
#59 
#58 
#57

Chore: Bump react version

---

yarn.lock

Yarn lock bump
```
[ ] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[x] Build related changes
[ ] CI related changes
[ ] Documentation content changes
[ ] Other... Please describe:
```
Bump Yarn lock
```
[ ] Yes
[x] No
```

yarn lock bump

---

package.json

chore(package): update electron-builder to version 20.0.5

---

package.json
yarn.lock

Greenkeeper/electron is dev 1.0.1

---

main.js

Closes #85 
- Winmoji when attempting to relaunch should check if there is another instance already running and use that.

fix(main): Winmoji singleInstance only

---

package.json
yarn.lock

Greenkeeper/electron builder 20.33.2

---

__tests__/app/containers/__snapshots__/Root.test.js.snap
package.json
yarn.lock

fix(test): Update emojilib update jest snapshot

---

appveyor.yml
package.json
yarn.lock

- bump node version to address #92 
- closes #92

fix: node version for electron-builder

---

main.js
yarn.lock

- Closes issue #102 
-- When application is in try it may not be minimized and simply closed. Need to check that the application is visible to restore. 
- unregister the correct global shortcut. 
- Attempt to click on the exe after the application is installed and running, but the window is closed (not minimized). 
nothing will happen, but winmoji is actually being focused the window is just not opened.

fix: Single instance bug when attempting to open exe

---

package.json
yarn.lock

Close #104 
Update coveralls to  3.0.5

chore(package): Coveralls 3.0.5

---

__mocks__/electron.js
package.json
yarn.lock

chore: Bump jest version

---

package.json
yarn.lock

Address set-value vulnerability

chore(security): Address set-value vul

---

yarn.lock

chore(yarn): Bump yarn.lock

---

main.js
package.json
yarn.lock

security: upgrade packages

---

.github/ISSUE_TEMPLATE/bug_report.md
.github/PULL_REQUEST_TEMPLATE.md
.github/workflows/codeql-analysis.yml
.prettierignore
.prettierrc
CODE_OF_CONDUCT.md
CONTRIBUTING.md
README.md
__mocks__/electron.js
__tests__/app/app.test.js
__tests__/app/containers/Root.test.js
__tests__/main.test.js
app/app.js
app/components/EmojiList.js
app/components/Search.js
app/containers/Root.js
app/windows/about.js
app/windows/index.js
appveyor.yml
css/style.css
main.js
package.json
tray.js
updater.js
webpack.config.js
yarn.lock

- Replace standard formatting with prettier.

fix: replace standard with prettier

---

.prettierignore
CONTRIBUTING.md
app/containers/Root.js
app/static/about.html
css/style.css
package.json

- Clean up pretteir items,
- Add a title for recently used emojis
- update copyright dates

feat: CLeanup

---

yarn.lock

- Address security in sub development packages.

security: yarn upgrade

---

app/static/about.html
css/style.css

- Update font used in application to use the systems default front (noted from https://github.com/ryanSN/winmoji/issues/162)
- Update CSS from the about us page into the one central location.

fix(UI): Update fonts used

---

index.html
package.json
yarn.lock

- Upgrade to Electron 11
- Add security issue

feat: Upgrade to Electron 11

---

.github/workflows/CI.yml
package.json

chore(ci): CI update

---

LICENSE.md

change to markdown and remove the year.

chore(license): Change to markdown

---

app/components/EmojiList.js
app/components/Search.js
app/containers/Root.js
app/main.js

- Switch root over to hooks. (address anon function performance issue)

feat: switch root to hooks

---

app/containers/Root.js
package.json
yarn.lock

fix: Address focus error

---

package.json
yarn.lock

feat: Upgrade webpack to v5

---

src/components/Search/Search.tsx
src/components/TitleBar/TitleBarStyles.ts
src/containers/Home.tsx
src/index.css

feat: update styles for 3.0.0 ui changes
